### ISSUE TITLE
Provide way to view facilities in a certain area

### ISSUE THREAD

**Issue by DGalt** [open-retirement/open-retirement.github.com#1]
Currently users must input an address to populate the map with facilities around that address. It would be useful to also offer the option to simply select a region (neighborhood in Chicago, zip code, something) from a dropdown or something similar that would then populate the map with facilities in that region.

**Comment by ziegegeist** [comment]
If you go to https://www.dnainfo.com/chicago and click on neighborhoods, I think that's most of Chicago covered. People might want to search a wider area, though. Would North Side, South Side, West Side and Loop be too big?

**Comment by pjsier** [comment]
This should be handled by [the most recent commit](https://github.com/open-retirement/nursing_home_leaflet/commit/5e42d68e25630bbf18a3c77ec906a6931fe4de05) for the most part.

Could still use improvement, but working much better now. Let me know if this misses anything in here!
