### ISSUE TITLE
Add Phone Numbers of Homes

### ISSUE THREAD

**Issue by ziegegeist** [open-retirement/open-retirement.github.com#11]
I know it's in here somewhere, but I can't figure out how to do it. 
[script.js](https://github.com/open-retirement/open-retirement.github.com/blob/master/js/script.js)

**Comment by pjsier** [comment]
@ziegegeist can update that now!

**Comment by pjsier** [comment]
Just addressed, and should be reflected in the tooltips on the new sites. Closing it now
