### ISSUE TITLE
Search button doesn't seem to work

### ISSUE THREAD

**Issue by ziegegeist** [open-retirement/open-retirement.github.com#16]
I suppose this is a known issue, but I wanted to put it in here. Also, some of the nonprofits we've been talking to have been coming to the site here and there. Should we put "beta" on it somewhere so that folks know?

**Comment by pjsier** [comment]
Which part of it isn't working? For addresses it should definitely work, but for nursing home names and zip codes usually you'll have to select something that shows up in autocomplete (which we could definitely clarify). If one of those isn't working past that though, then we could see what's going on. Also, I think putting in beta is a good idea!

**Comment by ziegegeist** [comment]
Oh! I always just use zip code. I can write that into the little explanation text.

**Comment by pjsier** [comment]
@ziegegeist just fixed zip code! If that's the only search problem for now we can close this, otherwise let me know any others that are coming up

**Comment by ziegegeist** [comment]
You're the best! Works like a charm
