### ISSUE TITLE
Use zip code or condensed neighborhoods for boundary search

### ISSUE THREAD

**Issue by pjsier** [open-retirement/open-retirement.github.com#2]
Neighborhoods are currently too small/granular, either make the bounding boxes bigger or use zip codes for the dropdown search

**Comment by pjsier** [comment]
Switched to zip codes, but like I think @ziegegeist mentioned, there are a ton of those too. Could also make it so they're just autocomplete suggestions instead of a massive dropdown

**Comment by pjsier** [comment]
Changed zip to autocomplete for Chicago zip codes. It looks a lot better to me, but we can decide based on what people think. The changes is live at the url if people want to check it out [demo](http://open-retirement.github.io/nursing_home_leaflet/)

**Comment by ziegegeist** [comment]
With zip codes maybe we don't even need the address option. Looks good, though!

**Comment by DGalt** [comment]
With the zip code, if you actually type in the whole zip code you still need to select the one from the dropdown (hitting enter or anything like that doesn't activate the search)

**Comment by pjsier** [comment]
We have both options, can move back to neighborhoods if people want.
