### ISSUE TITLE
Zipcode search only works when a partial number/value is entered

### ISSUE THREAD

**Issue by ladytmarie** [open-retirement/open-retirement.github.com#5]
When searching by zip code, if the entire zipcode is entered into the top search box the search doesn't work.  If only the first few numbers are entered and a value is selected from the drop down menu, the search works.

**Comment by pjsier** [comment]
@ladytmarie not sure if I fully understood this, but I added a listener on `keyup` for users pressing enter so that people can search a zip code without having to select it from autocomplete first. Is that what you were referring to?

**Comment by ladytmarie** [comment]
Yes, now when I type a complete zipcode and hit enter the search works without having to select it from autocomplete first. 

This issue is resolved.  Thanks.
